auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: MicLee's Blog
url: http://ofmiclee.github.io
feed: /atom.xml
author_info: <a href="http://ofmiclee.github.io.com/">MicLee</a>
